100.oceanbase-database=关于 OceanBase 数据库
200.quick-start=快速入门
  600.basic-operations=基本操作
300.performance-whitepaper=性能白皮书
400.installation-and-deployment=安装部署
500.oceanbase-database-overview=OceanBase 数据库系统概念
  200.oceanbase-database-overview-data-distribution=数据分布
  300.data-model=数据模型
  400.high-availability=高可用
  500.transaction-management=事务管理
  600.storage-architecture=存储架构
  700.sql-engine=SQL 引擎
    200.oceanbase-database-overview-query-rewrite=查询改写
    300.oceanbase-database-overview-query-optimization=查询优化
      100.oceanbase-database-overview-access-path=访问路径
      200.oceanbase-database-overview-join-algorithm=联接算法
    400.oceanbase-database-overview-sql-execution-plan=SQL 执行计划
      200.oceanbase-database-overview-execution-plan-operators=执行计划算子
    500.oceanbase-database-overview-distributed-execution-plan=分布式执行计划
  800.backup-and-recovery=备份与恢复
600.administrator-guide=管理员指南
  200.database-management-tools=数据库管理工具介绍
  300.basic-database-management=数据库基础管理
    100.oceanbase-cluster-management=OceanBase 集群管理
      200.cluster-parameter-management=集群参数管理
    200.zone-management=Zone 管理
    300.observer-management=OBServer 管理
    400.resource-management=资源管理
    500.tenant-management=租户管理
    600.memory-management=内存管理
  400.database-object-management=数据库对象管理
    100.manage-tables=管理表
    200.manage-table-groups=管理表组
    300.manage-indexes=管理索引
  500.data-distribution-and-path-management=数据分布和链路管理
    100.manage-partitioned-tables-and-partitioned-indexes=分区表和分区索引管理
      300.create-a-partitioned-table=创建分区表
      600.create-an-index-on-a-partitioned-table=在分区表上建立索引
      700.maintain-partitioned-tables=维护分区表
    200.manage-replicas=副本管理
    300.locality-management=Locality 管理
  600.manage-transactions=事务管理
  700.manage-user-privileges=用户权限管理
  800.high-data-availability=数据高可用
    100.recycle-bin-management=回收站管理
    200.manage-backup-and-restoration=备份恢复管理
      300.data-backup=备份数据
        500.clear-backup-data=备份数据清理
      400.restore-data=恢复数据
      500.routine-maintenance=日常维护
700.developer-guide=开发者指南
  100.foreword=前言
    300.about-oceanbase-database=关于 OceanBase 数据库
      400.about-how-to-access-oceanbase-database=关于 OceanBase 数据库访问方式
  200.connect-to-oceanbase-database=连接 OceanBase 数据库
    500.query-table-data=查询表数据
      500.use-operators-and-functions-in-a-query=在查询中使用操作符和函数
  300.dml-statements-and-transactions=DML 语句和事务
    100.about-dml-statements=关于 DML 语句
  400.create-and-manage-database-objects=创建和管理数据库对象
    200.create-and-manage-tables=创建和管理表
    300.create-and-manage-partitioned-tables=创建和管理分区表
    400.create-and-manage-table-groups=创建和管理表组
    500.create-and-manage-views=创建和管理视图
  500.migrate-data-to-oceanbase-database=向 OceanBase 数据库迁移数据
  600.appendix=附录
800.best-practices=最佳实践
900.supporting-tools=生态工具
  100.ob-admin=ob-admin
  200.ob-agent=ob-agent
    100.about-obagent=关于 OBAgent
    200.configuration-reference=配置引用
    300.install-and-deploy-obagent=安装部署
    400.obagent-metrics=OBAgent 指标
  400.cdc=CDC
    200.liboblog=liboblog
      100.deploy-and-use-liboblog=liboblog 部署和使用
      200.liboblog-parameters=liboblog 参数说明
    300.oblogproxy=oblogproxy
      100.install-and-deploy-oblogproxy=安装部署
    400.oblogmsg=oblogmsg
  600.tableapi=TableAPI
    100.introduction-to-tableapi=TableAPI 介绍
    200.use-of-the-tableapi-client=客户端使用
1000.sql-reference=SQL 参考
  100.sql-reference-elements=基本元素
    100.sql-reference-data-types=数据类型
      200.numeric-data-types=数值类型
      300.date-and-time-data-types=日期时间类型
      400.character-data-types=字符类型
      500.blob-and-text-data-types=大对象和文本类型
    200.sql-reference-expressions=表达式
    300.character-sets-and-collations=字符集与字符序
    400.sql-reference-literals=字面量
  200.operator=运算符
  300.sql-reference-functions=函数
    200.single-row-functions=单行函数
      100.date-and-time-functions=日期时间函数
      200.string-functions=字符串函数
      300.conversion-functions=转换函数
      400.mathematical-functions=数学函数
      500.comparison-functions=比较函数
      600.process-control-functions=流程控制函数
    300.sql-reference-aggregate-functions=聚合函数
    400.sql-reference-analytic-functions=分析函数
    500.sql-reference-information-functions=信息函数
    600.sql-reference-other-functions=其他函数
  400.sql-reference-queries-and-subqueries=查询和子查询
  500.sql-statement=SQL语句
    600.sql-statements-alter-system=ALTER SYSTEM
    5600.sql-statements-select=SELECT
1200.sql-tuning-guide=SQL 调优指南
  200.sql-execution-plan=SQL 执行计划
    200.execution-plan-operators=执行计划算子
  300.distributed-execution-plan=分布式执行计划
  400.sql-tuning=SQL 优化
    300.monitor-the-sql-execution-performance=SQL 执行性能监控
      400.examples-of-sql-performance-analysis=SQL 性能分析示例
    400.query-rewrite=查询改写
    500.query-optimization=查询优化
      100.access-path=访问路径
      200.join-algorithm=联接算法
    600.manage-execution-plans=管理执行计划
1300.reference-guide=参考指南
  100.system-views=系统视图
    100.dictionary-views=字典视图
    200.performance-views=性能视图
  200.system-variables=系统变量
  300.system-configuration-items=系统配置项
  400.error-codes=错误码
1400.community-contribution=社区贡献
