1.oceanbase-database=关于 OceanBase 数据库
2.quick-start=快速入门
  6.basic-operations=基本操作
3.performance-whitepaper=性能白皮书
4.installation-and-deployment=安装部署
5.oceanbase-database-overview=OceanBase 数据库系统概念
  1.introduction-to-oceanbase-database=OceanBase 数据库简介
  2.multi-tenant-architecture=多租户架构
    5.tenant-and-resource-management=租户与资源管理
  3.database-objects=数据库对象
    2.mysql-mode=MySQL 模式
      1.mysql-mode-introduction-to-database-objects=数据库对象介绍
      2.mysql-mode-tables=表
        2.mysql-mode-data-types=数据类型
      3.mysql-mode-indexes=索引
      4.mysql-mode-partitions=分区
      5.mysql-mode-views=视图
      6.mysql-mode-system-views=系统视图
      7.mysql-mode-data-integrity=数据完整性
        2.mysql-mode-types-of-integrity-constraints=完整性约束类型
  4.distributed-database-objects=分布式数据库对象
    3.partitions-and-replicas=数据分区和分区副本概述
      2.replica-types=分区副本类型
      4.data-balancing=数据均衡
        1.replica-balancing=分区副本均衡
        2.leader-balancing=Leader 均衡
    4.dynamic-scale-out-and-scale-in=动态扩容和缩容
      2.scale-out-and-scale-in-of-tenant-resources=租户内资源的扩容和缩容
  5.data-links=数据链路
    2.database-proxy=数据库代理
    3.database-drivers=数据库驱动
  6.user-interfaces-and-query-languages=用户接口和查询语言
    1.sql=SQL
      1.introduction-to-sql=SQL 介绍
      2.oceanbase-database-overview-sql-statements=SQL 语句
      5.distributed-execution-plans=分布式执行计划
    2.pl=PL
      1.pl-concepts=PL 概念
        1.pl-oracle-mode=Oracle 模式
        2.pl-mysql-mode=MySQL 模式
  7.transaction-management=事务管理
    1.transactions=事务
      5.transaction-control=事务控制
        4.transaction-control-statements=事务控制语句
      8.distributed-transactions=分布式事务
    2.transaction-concurrency-and-consistency=事务并发和一致性
      3.concurrency-control=并发控制
      4.transaction-isolation-levels=事务隔离级别
  8.storage-architecture=存储架构
    2.data-storage=数据存储
    3.minor-compaction-and-major-compaction=转储和合并
    6.storage-architecture-data-integrity=数据完整性
  9.data-reliability-and-high-availability=数据可靠性和高可用
    1.high-availability-architecture=高可用架构
    4.data-protection=数据保护
    5.backup-and-recovery=备份恢复
  10.database-security=数据库安全
  11.observer-architecture=OBServer 节点架构
    3.observer-threading-model=observer 线程模型
    5.oceanbase-database-overview-memory-management=内存管理
6.administrator-guide=管理员指南
  1.introduction-to-database-management=数据库管理入门
    3.administrator-guide-connect-to-oceanbase-database=连接数据库
    4.view-your-database-version=查看您的数据库版本
  2.basic-database-management=数据库基础管理
    1.manage-clusters=管理集群
      3.manage-cluster-parameters=管理集群参数
      4.manage-zones-in-a-cluster=管理集群中的 Zone
      5.manage-observers=管理 OBServer
    2.configuration-management=配置管理
    3.manage-resources=管理资源
      3.manage-resource-units=资源管理单元
      5.manage-resource-pools=管理资源池
    4.manage-tenants=管理租户
      4.administrator-guide-manage-tenants=管理租户
      5.manage-users-and-privileges=管理用户和权限
        1.introduction-to-users-and-privileges=用户及权限介绍
      13.manage-tenant-parameters=管理租户参数
    5.manage-data-storage=管理数据存储
      1.minor-compaction-management=转储管理
      2.major-compaction-management=合并管理
        5.view-major-compaction-information=查看合并信息
    6.manage-memory=管理内存
    7.manage-processes=管理进程
    8.manage-logs=管理日志
      2.administrator-guide-log-print-level=日志打印级别
      3.manage-the-size-and-number-of-log-files=日志文件大小及数量管理
      4.view-logs=查看日志
    9.scale-out-and-scale-in=扩容和缩容
      2.cluster-level-scale-out-and-scale-in=集群级别的扩容和缩容
        1.scale-out=扩容
        2.scale-in=缩容
      3.administrator-guide-scale-out-and-scale-in-of-tenant-resources=租户内资源的扩容和缩容
  3.database-connection-and-routing=数据库连接和路由
    3.logical-connection=逻辑连接
    4.driver-management=驱动管理
    5.routing-management=路由管理
      4.odp-routing-policy=ODP 路由策略
  4.database-object-management=数据库对象管理
    1.manage-databases=管理数据库
    2.manage-tables=管理表
    3.manage-table-groups=管理表组
    4.manage-indexes=管理索引
  5.distributed-storage-management=分布式存储管理
    2.manage-partitions=管理分区
      8.create-an-index-on-a-partitioned-table=创建分区表索引
    3.manage-replicas=管理副本
    4.manage-locality=管理 Locality
    5.load-balancing=负载均衡
      3.manually-manage-load-balancing=手动管理负载均衡
  7.high-data-availability=数据高可用
    1.administrator-guide-flashback=闪回
    2.backup-and-recovery-management=备份恢复管理
      3.cluster-level-data-backup=备份数据（集群级别）
      4.data-recovery=恢复数据
      5.routine-maintenance=日常维护
  8.administrator-guide-monitoring-and-alerts=监控和告警
    1.use-ocp-to-monitor-databases=通过 OCP 监控数据库
      2.monitoring=监控
      3.alerts=告警
7.developer-guide=开发者指南
  1.foreword=前言
    3.about-oceanbase-database=关于 OceanBase 数据库
      4.about-how-to-access-oceanbase-database=关于 OceanBase 数据库访问方式
  2.connect-to-oceanbase-database=连接 OceanBase 数据库
    5.query-table-data=查询表数据
      5.use-operators-and-functions-in-a-query=在查询中使用操作符和函数
  3.dml-statements-and-transactions=DML 语句和事务
    1.about-dml-statements=关于 DML 语句
  4.create-and-manage-database-objects=创建和管理数据库对象
    2.create-and-manage-tables=创建和管理表
    3.create-and-manage-partitioned-tables=创建和管理分区表
    4.create-and-manage-table-groups=创建和管理表组
    5.create-and-manage-views=创建和管理视图
  5.migrate-data-to-oceanbase-database=向 OceanBase 数据库迁移数据
  6.appendix=附录
8.best-practices=最佳实践
9.supporting-tools=生态工具
  1.ob-admin=ob-admin
  2.ob-agent=OBAgent
    1.about-obagent=关于 OBAgent
    2.configuration-reference=配置引用
    3.install-and-deploy-obagent=安装部署
    4.obagent-metrics=OBAgent 指标
  4.cdc=CDC
    2.liboblog=liboblog
      1.deploy-and-use-liboblog=liboblog 部署和使用
      2.liboblog-parameters=liboblog 参数说明
    3.oblogproxy=oblogproxy
      1.install-and-deploy-oblogproxy=安装部署
    4.oblogmsg=oblogmsg
  6.tableapi=TableAPI
    1.introduction-to-tableapi=TableAPI 介绍
    2.use-of-the-tableapi-client=客户端使用
  8.hbaseapi=HBaseAPI
10.sql-reference=SQL 参考
  1.elements=基本元素
    1.data-types=数据类型
      2.numeric-data-types=数值类型
      3.date-and-time-data-types=日期时间类型
      4.character-data-types=字符类型
      5.blob-and-text-data-types=大对象和文本类型
    2.expressions=表达式
    3.character-sets-and-collations=字符集与字符序
    4.literals=字面量
  2.operators=运算符
  3.functions=函数
    2.single-row-functions=单行函数
      1.date-and-time-functions=日期时间函数
      2.string-functions=字符串函数
      3.conversion-functions=转换函数
      4.mathematical-functions=数学函数
      5.comparison-functions=比较函数
      6.process-control-functions=流程控制函数
    3.aggregate-functions=聚合函数
    4.analytic-functions=分析函数
    5.encryption-functions=加密函数
    6.information-functions=信息函数
    7.other-functions=其他函数
  4.queries-and-subqueries=查询和子查询
  5.sql-statements=SQL语句
    6.alter-system=ALTER SYSTEM
    56.sql-statements-select=SELECT
11.sql-tuning-guide=SQL 调优指南
  2.sql-execution-plan=SQL 执行计划
    2.execution-plan-operators=执行计划算子
  3.distributed-execution-plan=分布式执行计划
  4.sql-tuning=SQL 优化
    3.monitor-the-sql-execution-performance=SQL 执行性能监控
      4.examples-of-sql-performance-analysis=SQL 性能分析示例
    4.query-rewrite=查询改写
    5.query-optimization=查询优化
      1.access-path=访问路径
      2.join-algorithm=联接算法
    6.manage-execution-plans=管理执行计划
12.reference-guide=参考指南 
  1.system-views=系统视图
    1.dictionary-views=字典视图
    2.performance-views=性能视图
  2.system-variables=系统变量
  3.system-configuration-items=系统配置项
  4.error-codes=错误码
13.community-contribution=社区贡献
