100.oceanbase-database=关于 OceanBase 数据库
200.quick-start=快速入门
  600.basic-operations=基本操作
300.performance-whitepaper=性能白皮书
400.installation-and-deployment=安装部署
500.oceanbase-database-overview=OceanBase 数据库系统概念
  200.oceanbase-database-overview-data-distribution=数据分布
  300.data-model=数据模型
  400.high-availability=高可用
  500.transaction-management=事务管理
  600.storage-architecture=存储架构
  700.sql-engine=SQL 引擎
    200.oceanbase-database-overview-query-rewrite=查询改写
    300.oceanbase-database-overview-query-optimization=查询优化
      100.oceanbase-database-overview-access-path=访问路径
      200.oceanbase-database-overview-join-algorithm=联接算法
    400.oceanbase-database-overview-sql-execution-plan=SQL 执行计划
      200.oceanbase-database-overview-execution-plan-operators=执行计划算子
    500.oceanbase-database-overview-distributed-execution-plan=分布式执行计划
600.administrator-guide=管理员指南
  200.database-management-tools=数据库管理工具介绍
  300.basic-database-management=数据库基础管理
    100.oceanbase-cluster-management=OceanBase 集群管理
      200.cluster-parameter-management=集群参数管理
    200.zone-management=Zone 管理
    300.observer-management=OBServer 管理
    400.resource-management=资源管理
    500.tenant-management=租户管理
    600.memory-management=内存管理
  400.database-object-management=数据库对象管理
    100.manage-tables=管理表
    200.manage-table-groups=管理表组
    300.manage-indexes=管理索引
    400.manage-views-and-synonyms=视图和同义词管理
  500.data-distribution-and-path-management=数据分布和链路管理
    100.manage-partitioned-tables-and-partitioned-indexes=分区表和分区索引管理
      300.create-a-partitioned-table=创建分区表
      600.create-an-index-on-a-partitioned-table=在分区表上建立索引
      700.maintain-partitioned-tables=维护分区表
    200.manage-replicas=副本管理
    300.locality-management=Locality 管理
  600.manage-transactions=事务管理
  700.manage-user-privileges=用户权限管理
  800.high-data-availability=数据高可用
    100.recycle-bin-management=回收站管理
700.developer-guide=开发者指南
  100.foreword=前言
    300.about-oceanbase-database=关于 OceanBase 数据库
      400.about-how-to-access-oceanbase-database=关于 OceanBase 数据库访问方式
  200.connect-to-oceanbase-database=连接 OceanBase 数据库
    500.query-table-data=查询表数据
      500.use-operators-and-functions-in-a-query=在查询中使用操作符和函数
  300.dml-statements-and-transactions=关于 DML 语句和事务
    100.about-dml-statements=关于 DML 语句
  400.create-and-manage-database-objects=创建和管理数据库对象
    200.create-and-manage-tables=创建和管理表
    300.create-and-manage-partitioned-tables=创建和管理分区表
    400.create-and-manage-table-groups=创建和管理表组
    500.create-and-manage-views=创建和管理视图
  500.migrate-data-to-oceanbase-database=向 OceanBase 迁移数据
  600.appendix=附录
800.sql-reference=SQL 参考
  100.elements=基本元素
  200.operators=运算符
  300.function=函数
  400.queries-and-subqueries=查询和子查询
  500.sql-statements=SQL语句
900.sql-tuning-guide=SQL 调优指南
  200.sql-execution-plan=SQL 执行计划
    200.execution-plan-operators=执行计划算子
  300.distributed-execution-plan=分布式执行计划
  400.sql-tuning=SQL 优化
    300.monitor-the-sql-execution-performance=SQL 执行性能监控
      400.examples-of-sql-performance-analysis=SQL 性能分析示例
    400.query-rewrite=查询改写
    500.query-optimization=查询优化
      100.access-path=访问路径
      200.join-algorithm=联接算法
    600.manage-execution-plans=管理执行计划
1000.reference-guide=参考指南
  100.system-views=系统视图
    100.dictionary-views=字典视图
    200.performance-views=性能视图
  200.system-variables=系统变量
  300.system-configuration-items=系统配置项
1100.community-contribution=社区贡献
